### ISSUE TITLE
Tests failing for the following files:

### ISSUE THREAD

**Issue by rmathew1011** [TAMULib/weaver-components#298]
1. WvrDropdownComponent should toggle the dropdown on click event.
`projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts:174:10`
2. WvrDropdownComponent should not close the dropdown on click inside.
`at projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts:236:10`
3. WvrDropdownComponent should close the dropdown on click outside.
`at projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts:218:10`
4. WvrDropdownComponent should open the dropdown on mouseenter event.
` at projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts:145:10`
5. WvrDropdownComponent should not close the dropdown on mouseleave event, if `toggleOn` is set to "click".
`at projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts:206:10`
6. WvrDropdownComponent should report open status with `isOpen` method.
`at projects/wvr-elements/src/lib/wvr-dropdown/wvr-dropdown.component.spec.ts:128:10`
7. WvrHeaderComponent should have bottom navigation toggle display
`projects/wvr-elements/src/lib/wvr-header/wvr-header.component.spec.ts:97:29`

**Comment by rmathew1011** [comment]
William resolved this issue.
Reason: _The problem was running in GitHub actions the headless browser was reporting in mobile view. As our tests should handle both and be isolated from this, I added a mock mobile service to override the provided mobile service. This allowed setting is mobile view to false. Also will allow testing both scenarios now._
